---
# Written by Dridi Boukelmoune <dridi.boukelmoune@gmail.com>
#
# This file is in the public domain.

sudo: required
dist: focal

language: c

addons:
  apt:
    packages:
    - debhelper
    - debian-archive-keyring
    - dpkg-dev
    - fakeroot
    - lcov
    - pbuilder
    - python3-docutils
    - python3-sphinx
    - sbuild
    - schroot

compiler:
  - clang
  - gcc

env:
  matrix:
    - CFLAGS=-O0
    - CFLAGS=-O1
    - CFLAGS=-O2
    - CFLAGS=-O3
    - CFLAGS=-Os
    - MAKE_TARGET=distcheck
    - VARNISH_BRANCH=master
    - VARNISH_BRANCH=6.0

matrix:
  include:
    - compiler: gcc
      env: MAKE_TARGET=deb DPKG_BUILDPACKAGE_OPTS='-d'
    - compiler: gcc
      env: MAKE_TARGET=pdebuild PDEBUILD_OPTS='-- --debug'
    - compiler: gcc
      env: MAKE_TARGET=sbuild SBUILD='sudo sbuild' SBUILD_OPTS='--dist buster'
    - compiler: gcc
      env: MAKE_TARGET=lcov CONFIGURE_FLAGS=--enable-lcov

  # dpkg doesn't accept "trunk" as a version
  allow_failures:
    - compiler: gcc
      env: MAKE_TARGET=deb DPKG_BUILDPACKAGE_OPTS='-d'
    - compiler: gcc
      env: MAKE_TARGET=pdebuild PDEBUILD_OPTS='-- --debug'
    - compiler: gcc
      env: MAKE_TARGET=sbuild SBUILD='sudo sbuild' SBUILD_OPTS='--dist buster'

install:
  - set -e
  - travis/install_varnish.sh
  - travis/create_pbuilder.sh
  - travis/create_sbuild.sh

script:
  - ./bootstrap $CONFIGURE_FLAGS
  - make ${MAKE_TARGET:-check} VERBOSE=1

after_success:
  - test "$MAKE_TARGET" = lcov || exit 0
  - cp vmod-querystring.info codecov.info
  - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy
